[build]
  base = "frontend"
  command = "npm install && ng build --configuration production"
  publish = "frontend/dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
